[project]
name = "re2c-to-automaton"
version = "0.1.0"
description = "Imports re2c DFAs (via graphviz) to automata-lib"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "automata-lib>=8.4.0",
    "click>=8.1.8",
    "pytest>=8.3.4",
    "ruff>=0.9.1",
]
